# Generated by Django 4.2.1 on 2023-05-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id_publisher', models.IntegerField(primary_key=True, serialize=False)),
                ('name_publisher', models.CharField(max_length=100)),
                ('isbn_publisher', models.IntegerField(blank=True)),
                ('email_publisher', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
