# Generated by Django 4.2.1 on 2023-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_warstwy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.IntegerField(primary_key=True, serialize=False)),
                ('title_book', models.CharField(max_length=100)),
                ('year_book', models.IntegerField()),
                ('edition_book', models.IntegerField(blank=True)),
                ('isbn_book', models.IntegerField(blank=True)),
                ('form_book', models.CharField(blank=True, max_length=15)),
                ('cover_book', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id_deposit', models.IntegerField(primary_key=True, serialize=False)),
                ('title_deposit', models.CharField(max_length=100)),
                ('year_deposit', models.IntegerField()),
                ('edition_deposit', models.IntegerField(blank=True)),
                ('isbn_deposit', models.IntegerField(blank=True)),
                ('form_deposit', models.CharField(blank=True, max_length=15)),
                ('cover_deposit', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
